name: PR

on:
  push: {}
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Go Build
        env:
          GOOS: js
          GOARCH: wasm
        run: go build ./...

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install chrome
        uses: browser-actions/setup-chrome@latest

      - name: Go Test
        run: make -C tests test

      - uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: tests/.coverage/coverage.html

  features:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Go Test
        run: make -C examples/features test
